<?php
declare(strict_types=1);

use Miklcct\NationalRailTimetable\Views\Components\AllPortions;
use Miklcct\NationalRailTimetable\Views\Components\Portion;

/** @var AllPortions $this */

$joins = $this->service->joins;
$divides = $this->service->divides;
?>
<table class="portion">
<?php
if ($joins) {
?>
    <tr>
        <td>
            <table class="portion">
                <tr>
<?php
    foreach ($joins as $i => $portion) {
?>
                    <td>
<?php
        echo new AllPortions(
            $this->getStreamFactory()
            , $this->dateFromOrigin
            , $portion
            , $this->permanentOnly
            , $this->wtt
            , $this->fromViewMode
        );
?>
                    </td>
<?php
    }
?>
                </tr>
            </table>
        </td>
    </tr>
<?php
}
?>
    <tr>
        <td>
<?php
echo new Portion(
    $this->getStreamFactory()
    , $this->dateFromOrigin
    , $this->service
    , $this->permanentOnly
    , $this->wtt
    , $this->fromViewMode
);
?>
        </td>
    </tr>
<?php
if ($divides) {
?>
    <tr>
        <td>
            <table class="portion">
                <tr>
<?php
    foreach ($divides as $i => $portion) {
?>
                    <td>
<?php
        echo new AllPortions(
            $this->getStreamFactory()
            , $this->dateFromOrigin
            , $portion
            , $this->permanentOnly
            , $this->wtt
            , $this->fromViewMode
        );
?>
                    </td>
<?php
    }
?>
                </tr>
            </table>
        </td>
    </tr>
<?php
}
?>
</table>