<?php
declare(strict_types = 1);
    
use Miklcct\NationalRailTimetable\Controllers\BoardController;
use Miklcct\NationalRailTimetable\Views\Components\Board;
use Miklcct\NationalRailTimetable\Views\ServiceView;
use Miklcct\NationalRailTimetable\Views\ViewMode;
use Miklcct\RailOpenTimetableData\Models\Location;
use Miklcct\RailOpenTimetableData\Models\ServiceCall;
use function Miklcct\NationalRailTimetable\Views\get_arrival_link;
use function Miklcct\NationalRailTimetable\Views\get_header_classes;
use function Miklcct\NationalRailTimetable\Views\get_service_property;
use function Miklcct\NationalRailTimetable\Views\show_activities;
use function Miklcct\NationalRailTimetable\Views\show_facilities;
use function Miklcct\NationalRailTimetable\Views\show_short_term_planning;
use function Miklcct\NationalRailTimetable\Views\show_time;
use function Miklcct\NationalRailTimetable\Views\show_toc;
use function Miklcct\ThinPhpApp\Escaper\html;

/** @var Board $this */

$query = $this->query;
$board = $this->board;
$station = $query->station;
?>
<table>
    <thead>
<?php
if ($query->timeType->isArrival()) {
?>
        <tr><th colspan="8"><a href="<?= $this->getDayOffsetLink(1) ?>">Next day</a></th></tr>
<?php
} else {
?>
        <tr><th colspan="8"><a href="<?= $this->getDayOffsetLink(-1) ?>">Previous day</a></th></tr>
<?php
}
?>
        <tr>
            <th>STP</th>
            <th>Time</th>
            <th></th>
            <th>Pl.</th>
            <th>TOC</th>
            <th>Train no.</th>
            <th><?= $query->timeType->isArrival() ? 'Origin' : 'Destination' ?></th>
            <th>Calling at</th>
        </tr>
    </thead>
    <tfoot>
<?php
if ($query->timeType->isArrival()) {
?>
        <tr><th colspan="8"><a href="<?= $this->getDayOffsetLink(-1) ?>">Previous day</a></th></tr>
<?php
} else {
?>
        <tr><th colspan="8"><a href="<?= $this->getDayOffsetLink(1) ?>">Next day</a></th></tr>
<?php
}
?>
    </tfoot>
    <tbody>
<?php
$previous_timestamp = null;
/**
 * @var ServiceCall $service_call
 */
foreach ($query->timeType->isArrival() ? array_reverse($this->board->calls, true) : $this->board->calls as $h => $service_call) {
    $timestamp = $service_call->getTimestamp($query->timeType);
    $destinations = $query->timeType->isArrival() ? $service_call->service->getOriginPortions() : $service_call->service->getDestinationPortions();
    $portions_count = count($destinations);
    $portion_uids = array_keys($destinations);
    $overtaken_portions = array_combine(
        $portion_uids
        , array_map(
            static fn(string $uid) : bool => count($query->filter) === 1
                && $board-> isPortionOvertaken(
                    $service_call,
                    $query->filter[0]->getCrsOrTiplocCode(),
                    $uid
                )
            , $portion_uids
        )
    );
    $whole_train_overtaken = !in_array(false, $overtaken_portions, true);
    $day_offset = $timestamp->setTime(0, 0)->diff($this->date->toDateTimeImmutable())->days;
?>
        <tr class="<?= implode(' ', [$h % 2 ? 'odd' : 'even', get_header_classes($service_call)]) ?>" data-timestamp="<?= html($timestamp->getTimestamp()) ?>">
            <td class="<?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>"><?= show_short_term_planning($service_call) ?></td>
            <td class="time <?=
            $query->connectingTime === null
                ? ''
                : ($service_call->isValidConnection($query->timeType, $query->connectingTime, $this->connectingToc ?? null) ? 'valid_connection' : 'invalid_connection')
            ?> <?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>">
                <?=
                show_time($timestamp, $this->date, ServiceView::getServiceUrl($service_call->service->uid, $service_call->service->date, $query->permanentOnly, ViewMode::BOARD))
                . show_activities($service_call->timingPoint->activities)
                ?>
            </td>
            <td class="<?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>"><?= show_facilities($service_call->service->mode, get_service_property($service_call, $query)) ?></td>
            <td class="<?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>"><?= html($service_call->timingPoint->platform) ?></td>
            <td class="<?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>"><?= show_toc($service_call->service->toc) ?></td>
            <td class="<?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>"><a href="<?= html(ServiceView::getServiceUrl($service_call->service->uid, $service_call->service->date, $query->permanentOnly, ViewMode::BOARD)) ?>"><?= html(substr(get_service_property($service_call, $query)->rsid, 2, 4)) ?></a></td>
<?php
    foreach ($portion_uids as $i => $uid) {
        if ($i > 0) {
?>
        </tr>
        <tr class="<?= implode(' ', [$h % 2 ? 'odd' : 'even', get_header_classes($service_call)]) ?>">
<?php
        }
?>
            <td class="destination <?= $overtaken_portions[$uid] ? 'overtaken' : '' ?>"><?= html(($query->timeType->isArrival() ? array_first($destinations[$uid]->timingPoints) : array_last($destinations[$uid]->timingPoints))->location->getShortName()) ?></td>
            <td class="calls <?= $overtaken_portions[$uid] ? 'overtaken' : '' ?>"><?=
                implode(
                    ', '
                    , array_map(
                        function(ServiceCall $service_call) use ($query) : string {
                            $station = $service_call->timingPoint->location;
                            $link = get_arrival_link(BoardController::URL, $service_call, $this->query);
                            /** @noinspection HtmlUnknownTarget */
                            return sprintf(
                                $link === null ? '<span class="%1$s">%3$s (%4$s)</span>' : '<span class="%s"><a href="%s">%s</a> (%s)</span>'
                                , $station instanceof Location && in_array($station->getCrsOrTiplocCode(), array_map(static fn(Location $destination) => $destination->getCrsOrTiplocCode(), $this->query->filter), true) ? 'destination' : ''
                                , html($link)
                                , html($station->getShortName())
                                , show_time($service_call->getTimestamp($query->timeType), $this->date) . show_activities($service_call->timingPoint->activities)
                            );
                        }
                        , array_filter(
                            $query->timeType->isArrival() ? $service_call->getPrecedingCalls(true) : $service_call->getSubsequentCalls(true)
                            , fn(ServiceCall $service_call) : bool => array_key_exists(
                                $uid,
                                $query->timeType->isArrival() ? $service_call->service->getOriginPortions() : $service_call->service->getDestinationPortions()
                            )
                        )
                    )
                )
            ?></td>
<?php
    }
?>
        </tr>
<?php
    $previous_timestamp = $timestamp;
}
?>
    </tbody>
</table>
