<?php
declare(strict_types=1);

use Miklcct\NationalRailTimetable\DomainModels\Points\HasArrival;
use Miklcct\NationalRailTimetable\DomainModels\Points\HasDeparture;
use Miklcct\NationalRailTimetable\DomainModels\Points\OriginOrIntermediatePoint;
use Miklcct\NationalRailTimetable\Enums\Activity;
use Miklcct\NationalRailTimetable\Enums\TimeType;
use Miklcct\NationalRailTimetable\Models\PhysicalStation;
use Miklcct\NationalRailTimetable\Views\Components\Portion;
use Miklcct\NationalRailTimetable\Views\Components\ServiceInformation;
use function Miklcct\NationalRailTimetable\Views\get_tiploc_data;
use function Miklcct\ThinPhpApp\Escaper\html;
use function Safe\json_encode;

/** @var Portion $this */

?>
<table class="calling_points" data-line="<?= html(json_encode($this->line)) ?>">
<?php
$points = $this->portion->timingPoints;
$service_property = null;
foreach ($points as $i => $point) {
    $show_arrival = $i !== 0 && $point instanceof HasArrival && $point->getPublicArrival() !== null;
    $show_departure = $i !== count($points) - 1 && $point instanceof HasDeparture && $point->getPublicDeparture() !== null;

    $tiploc_data = get_tiploc_data()[$point->location->tiploc_code] ?? null;

    $easting_northing = (
        $point->location instanceof PhysicalStation
        ? sprintf(
            'data-crs="%s" data-name="%s" data-easting="%d" data-northing="%d"',
            html($point->location->crs_code),
            html($point->location->getShortName()),
            $tiploc_data["easting"] ?? $point->location->easting,
            $tiploc_data["northing"] ?? $point->location->northing
        ) : ''
    ) . (in_array(Activity::REQUEST_STOP, $point->activities, true) ? ' data-request-stop="1"' : '');
    /** @noinspection TypeUnsafeComparisonInspection */
    /** @noinspection PhpNonStrictObjectEqualityInspection */
    if ($point instanceof OriginOrIntermediatePoint
            && $point->serviceProperty !== null && $point->serviceProperty != $service_property) {
        $service_property = $point->serviceProperty;

        if ($show_arrival && $point->isPublicCall()) {
?>
    <tr <?= $easting_northing ?>>
        <td><?= html($point->location->getShortName()) ?></td>
        <td><?= html($point->platform) ?></td>
        <td class="time"><?= $this->showTime($point, TimeType::PUBLIC_ARRIVAL) ?></td>
        <td class="time"></td>
        <td><?= implode('<br/>', array_filter(array_map(
                static fn(Activity $activity) => $activity->getDescription(), $point->activities))) ?></td>
    </tr>
    
<?php
        }
        echo new ServiceInformation($this->getStreamFactory(), $this->portion, $point->serviceProperty);
        
        if ($show_departure && $point->isPublicCall()) {
?>
    <tr <?= $easting_northing ?>>
        <td><?= html($point->location->getShortName()) ?></td>
        <td><?= html($point->platform) ?></td>
        <td class="time"></td>
        <td class="time"><?= $this->showTime($point, TimeType::PUBLIC_DEPARTURE) ?></td>
        <td><?= implode('<br/>', array_filter(array_map(
                static fn(Activity $activity) => $activity->getDescription(), $point->activities))) ?></td>
    </tr>
<?php
        }
    } elseif ($point->isPublicCall() && ($show_arrival || $show_departure)) {
?>
    <tr <?= $easting_northing ?>>
        <td><?= html($point->location->getShortName()) ?></td>
        <td><?= html($point->platform) ?></td>
        <td class="time"><?= $show_arrival ? $this->showTime($point, TimeType::PUBLIC_ARRIVAL) : '' ?></td>
        <td class="time"><?= $show_departure ? $this->showTime($point, TimeType::PUBLIC_DEPARTURE) : '' ?></td>
        <td><?= implode('<br/>', array_filter(array_map(
                static fn(Activity $activity) => $activity->getDescription(), $point->activities))) ?></td>
    </tr>
<?php
    }
}
?>
</table>
