<?php
declare(strict_types=1);

use Miklcct\NationalRailTimetable\Views\Components\AllPortions;
use Miklcct\NationalRailTimetable\Views\ServiceView;
use function Miklcct\NationalRailTimetable\Views\show_script_tags;
use function Miklcct\ThinPhpApp\Escaper\html;

/** @var ServiceView $this */
?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
<?php
show_script_tags('service.ts');
?>
        <link rel="stylesheet" href="/common.css" />
        <title>
            <?= html($this->getTitle() . ($this->permanentOnly ? ' (permanent timetable)' : '')) ?>
        </title>
    </head>
    <body>
        <header class="<?= html($this->permanentOnly ? 'permanent' : '') ?>">
            <div class="heading">
                <h1><?= html($this->getTitle()) ?></h1>
                <p><?= html($this->service->getTocName()) ?></p>
            </div>
            <a href="<?= html($this->fromViewMode->getUrl()) ?>">Home</a>
        </header>
        <main>
<?php
if ($this->permanentOnly) {
?>
            <p id="permanent_warning">Warning: Permanent timetable instead of actual timetable shown</p>
<?php
}
?>
            <div id="map"><div id="popup"></div></div>
<?php
$service = $this->service;
while ($service->divideFrom !== null) {
    $service = $service->divideFrom;
}
while ($service->joinTo !== null) {
    $service = $service->joinTo;
}
echo new AllPortions(
    $this->getStreamFactory()
    , $this->originPortion->date
    , $service
    , $this->permanentOnly
    , $this->fromViewMode
);
?>
        </main>
<?php
require __DIR__ . '/footer.phtml';
?>
    </body>
</html>