<?php
declare(strict_types=1);

use Miklcct\NationalRailTimetable\Controllers\BoardQuery;
use Miklcct\NationalRailTimetable\Controllers\TimetableController;
use Miklcct\NationalRailTimetable\Views\AllStationsView;
use Miklcct\NationalRailTimetable\Views\Components\Footer;
use Miklcct\RailOpenTimetableData\Enums\TimeType;
use function Miklcct\NationalRailTimetable\Views\show_script_tags;
use function Miklcct\ThinPhpApp\Escaper\html;

/** @var AllStationsView $this */
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
<?php
show_script_tags('schedule_form.ts');
?>
        <link rel="stylesheet" href="/common.css" />
        <title>All stations</title>
    </head>
    <body>
        <header>
            <h1>All stations</h1>
        </header>
        <main>
            <table>
                <thead>
                    <tr>
                        <th>Station</th><th>Departures</th><th>Arrivals</th>
                    </tr>
                </thead>
                <tbody>
<?php
foreach ($this->stations as $station) {
?>
                    <tr>
                        <td><?= html($station->name) ?></td>
                        <td><a href="<?= html((new BoardQuery(TimeType::PUBLIC_DEPARTURE, $station))->getUrl(TimetableController::URL)) ?>">Departures</a></td>
                        <td><a href="<?= html((new BoardQuery(TimeType::PUBLIC_ARRIVAL, $station))->getUrl(TimetableController::URL)) ?>">Arrivals</a></td>
                    </tr>
<?php
}
?>
                </tbody>
            </table>
        </main>
<?php
echo new Footer($this->getStreamFactory(), null);
?>
    </body>
</html>