<?php
declare(strict_types = 1);

use Miklcct\NationalRailTimetable\Controllers\BoardQuery;
use Miklcct\NationalRailTimetable\Controllers\TimetableController;
use Miklcct\NationalRailTimetable\Views\Components\Timetable as TimetableView;
use Miklcct\NationalRailTimetable\Views\ServiceView;
use Miklcct\NationalRailTimetable\Views\ViewMode;
use Miklcct\RailOpenTimetableData\DomainModels\Timetable;
use Miklcct\RailOpenTimetableData\Enums\ShortTermPlanning;
use Miklcct\RailOpenTimetableData\Models\Location;
use Miklcct\RailOpenTimetableData\Models\ServiceCall;
use function Miklcct\NationalRailTimetable\Views\get_arrival_link;
use function Miklcct\NationalRailTimetable\Views\get_header_classes;
use function Miklcct\NationalRailTimetable\Views\get_service_property;
use function Miklcct\NationalRailTimetable\Views\show_call_time;
use function Miklcct\NationalRailTimetable\Views\show_facilities;
use function Miklcct\NationalRailTimetable\Views\show_short_term_planning;
use function Miklcct\NationalRailTimetable\Views\show_toc;
use function Miklcct\ThinPhpApp\Escaper\html;

/**
 * @param ServiceCall[] $array
 * @param int $i
 * @return int
 */
function get_colspan(array $array, int $i) : int {
    $call = $array[$i];
    $colspan = 0;
    /** @noinspection TypeUnsafeComparisonInspection */
    while (
        isset($array[$i])
        && $array[$i]->service->uid === $call->service->uid
        && $array[$i]->callIndex == $call->callIndex
    ) {
        ++$colspan;
        ++$i;
    }
    return $colspan;
}

/** @var TimetableView $this */
foreach ($this->boards as $board) {
    $timetable = Timetable::generateFromBoard($board);
    $stations = $timetable->stations;
    $calls = $timetable->calls;

    $destinations = $board->getDestinations();
    // if the via point is a destination don't show it
    $via = $board->getViaPoint();
    if (array_find($destinations, static fn(Location $location) => $location->getCrsOrTiplocCode() === $via?->getCrsOrTiplocCode())) {
        $via = null;
    }
    $shown_stations = $this->getShownRows($timetable);
?>
        <section>
            <h2>Trains
                <?= $this->query->timeType->isArrival() && $destinations ? ' from ' . html(implode(', ', array_map(static fn(Location $location) => $location->getShortName(), $destinations))) : '' ?>
                <?= $via ? ' via ' . html($via->getShortName()) : '' ?>
                <?= !$this->query->timeType->isArrival() && $destinations ? ' towards ' . html(implode(', ', array_map(static fn(Location $location) => $location->getShortName(), $destinations))) : '' ?>
            </h2>
            <div class="container">
                <!--suppress Annotator, Annotator -->
                <table class="timetable">
                    <thead>
                        <tr class="info">
                            <th class="station_column">TOC</th>
<?php
    $i = 0;
    while (isset($calls[0][$i])) {
        $call = $calls[0][$i];
        $colspan = get_colspan($calls[0], $i);
?>
                            <th class="<?= get_header_classes($call) . ' service' ?>" colspan=<?= $colspan ?> data-timestamp="<?= html($calls[0][$i]->getTimestamp($this->query->timeType)->getTimestamp()) ?>">
                                <?= show_toc($call->service->toc) ?>
                            </th>
<?php
        $i += $colspan;
    }
?>
                        </tr>
                        <tr class="info">
                            <td class="station_column">STP</td>
<?php
    $i = 0;
    while (isset($calls[0][$i])) {
        $call = $calls[0][$i];
        $colspan = get_colspan($calls[0], $i);
?>
                            <td class="<?= get_header_classes($call) ?>" colspan=<?= $colspan ?> data-timestamp="<?= html($calls[0][$i]->getTimestamp($this->query->timeType)->getTimestamp()) ?>">
                                <?= show_short_term_planning($call) ?>
                            </td>
<?php
        $i += $colspan;
    }
?>
                        </tr>
                        <tr class="info">
                            <td class="station_column">Train ID</td>
<?php
    $i = 0;
    while (isset($calls[0][$i])) {
        $call = $calls[0][$i];
        $colspan = get_colspan($calls[0], $i);
        $i += $colspan;
?>
                            <td class="<?= get_header_classes($call) ?>" colspan=<?= $colspan ?>><?= html(get_service_property($call, $this->query)->identity) ?></td>
<?php
    }
?>
                        </tr>
                        <tr class="info">
                            <td class="station_column">Headcode</td>
<?php
    $i = 0;
    while (isset($calls[0][$i])) {
        $call = $calls[0][$i];
        $colspan = get_colspan($calls[0], $i);
        $i += $colspan;
?>
                            <td class="<?= get_header_classes($call) ?>" colspan=<?= $colspan ?>><?= html(get_service_property($call, $this->query)->headcode) ?></td>
<?php
    }
?>
                        </tr>
                        <tr class="info">
                            <td class="station_column">Origin</td>
<?php
    $i = 0;
    while (isset($calls[0][$i])) {
        $call = $calls[0][$i];
        if ($this->query->timeType->isArrival()) {
            foreach ($call->service->getOriginPortions() as $origin) {
                $location = array_first($origin->timingPoints)->location;
?>
                            <td class="<?= get_header_classes($call) ?>"><abbr title="<?= html($location->getShortName()) ?>"><?= html($location->crsCode) ?></abbr></td>
<?php
                ++$i;
            }
        } else {
            $colspan = get_colspan($calls[0], $i);
?>
                            <td class="<?= get_header_classes($call) ?>" colspan="<?= $colspan ?>">
<?php
            foreach ($call->service->getOriginPortions() as $origin) {
                $location = array_first($origin->timingPoints)->location;
?>
                                <abbr title="<?= html($location->getShortName()) ?>"><?= html($location->crsCode) ?></abbr>
<?php
            }
?>
                            </td>
<?php
            $i += $colspan;
        }
    }
?>
                        </tr>
                        <tr class="info">
                            <td class="station_column">Destination</td>
<?php
    $i = 0;
    while (isset($calls[0][$i])) {
        $call = $calls[0][$i];
        if (!$this->query->timeType->isArrival()) {
            foreach ($call->service->getDestinationPortions() as $destination) {
                $location = array_last($destination->timingPoints)->location;
?>
                            <td class="<?= get_header_classes($call) ?>"><abbr title="<?=
                                html($location->getShortName()) ?>"><?= html($location->crsCode) ?></abbr></td>
<?php
                ++$i;
            }
        } else {
            $colspan = get_colspan($calls[0], $i);
?>
                            <td class="<?= get_header_classes($call) ?>" colspan="<?= $colspan ?>">
<?php
            foreach ($call->service->getDestinationPortions() as $destination) {
                $location = array_last($destination->timingPoints)->location;
?>
                                <abbr title="<?= html($location->getShortName()) ?>"><?= html($location->crsCode) ?></abbr>
<?php
            }
?>
                            </td>
<?php
            $i += $colspan;
        }
    }
?>
                        </tr>
                        <tr class="info">
                            <td class="station_column">Facilities</td>
<?php
    $i = 0;
    while (isset($calls[0][$i])) {
        $call = $calls[0][$i];
        $colspan = get_colspan($calls[0], $i);
        $i += $colspan;
?>
                            <td class="<?= get_header_classes($call) ?>" colspan=<?= $colspan ?>><?= show_facilities($call->service->mode, get_service_property($call, $this->query)) ?></td>
<?php
    }
?>
                        </tr>
<?php
    $show_platforms = static function () use ($calls) {
?>
        <tr class="info">
            <td class="station_column">Platform</td>
<?php
        $i = 0;
        while (isset($calls[0][$i])) {
            $call = $calls[0][$i];
            $colspan = get_colspan($calls[0], $i);
            $i += $colspan;
?>
            <td class="<?= get_header_classes($call) ?>" colspan=<?= $colspan ?>><?= html($call->timingPoint->platform) ?></td>
<?php
        }
?>
        </tr>
<?php
    };
    if (!$this->query->timeType->isArrival()) {
        $show_platforms();
    }
?>
<?php
    foreach (array_keys($shown_stations) as $row_number => $i) {
        $station = $stations[$i];
        if ($i === 0 && $this->query->timeType->isArrival()) {
?>
                    </thead>
                    <tfoot>
<?php
        } elseif ($row_number === 1) {
            if ($this->query->timeType->isArrival()) {
                $show_platforms();
?>
                    </tfoot>
<?php
            } else {
?>
                    </thead>
<?php
            }
?>
                    <tbody>
<?php
        }
?>
                        <tr class="<?= $i === 0 ? 'origin' : '' ?> <?= $i !== 0 && in_array($station->getCrsOrTiplocCode(), array_map(static fn(Location $location) => $location->getCrsOrTiplocCode(), $this->query->filter), true) ? 'destination' : '' ?>">
                            <td class="station_column">
                                <div class="station_name">
                                    <span>

<?php
        if ($i !== 0) {
?>
                                        <a href="<?= html(new BoardQuery($this->query->timeType, $this->query->station, [$station], $this->query->inverseFilter, $this->query->date, $this->query->toc, $this->query->connectingTime, $this->query->connectingToc, $this->query->permanentOnly)->getUrl(
                                            TimetableController::URL
                                        )) ?>">
<?php
        }
?>
                                            <?= html($station->getShortName()) ?>
<?php
        if ($i !== 0) {
?>
                                        </a>
<?php
        }
        $is_arrival = $this->query->timeType->isArrival() === ($i === 0);
?>
                                    </span>
                                    <abbr class="departure_arrival" title="<?= html($is_arrival ? 'arrival' : 'departure') ?>"><?= html($is_arrival ? 'a' : 'd') ?></abbr>
                                </div>
                            </td>
<?php
        $j = 0;
        while (isset($calls[0][$j])) {
            $colspan = isset($calls[$i][$j]) ? get_colspan($calls[$i], $j) : 1;
            $connection_class =
                $this->query->connectingTime !== null
                ? array_reduce(range($j, $j + $colspan - 1), fn($carry, $item) => $carry || $calls[0][$item]->isValidConnection($this->query->timeType, $this->query->connectingTime, $this->query->connectingToc), false)
                    ? 'valid_connection'
                    : 'invalid_connection'
                : '';
            if (
                $i !== 0
                && isset($calls[$i][$j])
                && $board->isCallOvertaken(
                    $calls[0][$j]
                    , $calls[$i][$j]
                )
            ) {
                $connection_class .= ' overtaken';
            }
            if ($calls[0][$j]->service->shortTermPlanning !== ShortTermPlanning::PERMANENT) {
                $connection_class .= ' stp';
            }
            if (!isset($calls[$i][$j])) {
?>
                            <td class="<?= $connection_class ?>"></td>
<?php
                ++$j;
            } else {
                $call = $calls[$i][$j];
                $link = $i === 0
                    ? ServiceView::getServiceUrl($call->service->uid, $call->service->date, $this->query->permanentOnly, ViewMode::TIMETABLE, !$this->query->timeType->isPublic())
                    : get_arrival_link(TimetableController::URL, $calls[$i][$j], $this->query);
?>
                           <td class="<?= $connection_class ?>" colspan=<?= $colspan ?>><?= show_call_time($call, $i ? $this->query->timeType->getCompanion() : $this->query->timeType, $this->date, $link) ?></td>
<?php
                $j += $colspan;
            }
        }
?>
                        </tr>
<?php
    }
?>
                    </tbody>
                </table>
            </div>
        </section>
<?php
    }
?>
